[project]
name = "fastapiproject"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.127.0",
    "openai>=2.14.0",
    "sqlalchemy>=2.0.45",
    "uvicorn>=0.40.0",
]
